#!/usr/bin/env python3

from msbase.lab import Step, AbstractLab

train_step = Step("train", command = ["python2", "train.py", "--ca", "--train_emb"])
test_step  = Step("test",  command = ["python2", "test.py", "--ca", "--train_emb"])

class Lab(AbstractLab):
    def digest_output(self, name, output):
        return {}

lab = Lab("sqlnet", steps=[train_step, test_step])
lab.run()
